[[obstack]]
arch = "aarch64"
git-tree-sha1 = "ae16670000df3848b679c68efd809df4194b4d50"
libc = "glibc"
os = "linux"

    [[obstack.download]]
    sha256 = "623e53d718864488882f24b6c154224cec2fae88937386b17ac371e829a75149"
    url = "https://github.com/JuliaBinaryWrappers/obstack_jll.jl/releases/download/obstack-v1.2.3+0/obstack.v1.2.3.aarch64-linux-gnu.tar.gz"
[[obstack]]
arch = "aarch64"
git-tree-sha1 = "d26e515167eb3ae6857a4068579e14cc36d2c929"
libc = "musl"
os = "linux"

    [[obstack.download]]
    sha256 = "a5e4d26f36504aacf8de469dd82f99b8c2a33f32a0c50a7730f83038e103b5af"
    url = "https://github.com/JuliaBinaryWrappers/obstack_jll.jl/releases/download/obstack-v1.2.3+0/obstack.v1.2.3.aarch64-linux-musl.tar.gz"
[[obstack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e3a54878f81e88822347941150d229c462459d13"
libc = "glibc"
os = "linux"

    [[obstack.download]]
    sha256 = "b4ffe6b5050283944f417472ba0bb9035c072fe7b61a13ea57e1457947ec61c8"
    url = "https://github.com/JuliaBinaryWrappers/obstack_jll.jl/releases/download/obstack-v1.2.3+0/obstack.v1.2.3.armv6l-linux-gnueabihf.tar.gz"
[[obstack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4fc42070a301971415df5f8ad77c41039cf7b4d3"
libc = "musl"
os = "linux"

    [[obstack.download]]
    sha256 = "ccc16f07a7c5a172b1a04a305c060d5c3685b582674c867f5341715cb78bd727"
    url = "https://github.com/JuliaBinaryWrappers/obstack_jll.jl/releases/download/obstack-v1.2.3+0/obstack.v1.2.3.armv6l-linux-musleabihf.tar.gz"
[[obstack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b447a66272f3b6638a04786320053c298f5c6fcb"
libc = "glibc"
os = "linux"

    [[obstack.download]]
    sha256 = "71dc6f058a1bb9205282512a08d736453a710dd9478119921d22a50bb6ad6f2a"
    url = "https://github.com/JuliaBinaryWrappers/obstack_jll.jl/releases/download/obstack-v1.2.3+0/obstack.v1.2.3.armv7l-linux-gnueabihf.tar.gz"
[[obstack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9b2bccfbe6e88d586e8e544cf1da620c80a61777"
libc = "musl"
os = "linux"

    [[obstack.download]]
    sha256 = "f9cb243bc38e3f2702dcfcd9f81657bfe5273b9a3b6858fd2091eedf8ef09288"
    url = "https://github.com/JuliaBinaryWrappers/obstack_jll.jl/releases/download/obstack-v1.2.3+0/obstack.v1.2.3.armv7l-linux-musleabihf.tar.gz"
[[obstack]]
arch = "i686"
git-tree-sha1 = "f3e3aa5f93cf9767f58b7bf3e889dbea8d545049"
libc = "glibc"
os = "linux"

    [[obstack.download]]
    sha256 = "34d187fc0e6af2a230a26479b895008adc080d5d77ef2fd1f7bc6c7ac9b2ed28"
    url = "https://github.com/JuliaBinaryWrappers/obstack_jll.jl/releases/download/obstack-v1.2.3+0/obstack.v1.2.3.i686-linux-gnu.tar.gz"
[[obstack]]
arch = "i686"
git-tree-sha1 = "5f99f7a774a5bd32c1b635dd68df0c3866db489b"
libc = "musl"
os = "linux"

    [[obstack.download]]
    sha256 = "e770ddd840870b6e2cc760d1890d4909f9d6795a165fe2717e59b495f8f61d9c"
    url = "https://github.com/JuliaBinaryWrappers/obstack_jll.jl/releases/download/obstack-v1.2.3+0/obstack.v1.2.3.i686-linux-musl.tar.gz"
[[obstack]]
arch = "powerpc64le"
git-tree-sha1 = "c5ddf6ecae6bdeecc9c7ae91d62cc6ca8d0dd54c"
libc = "glibc"
os = "linux"

    [[obstack.download]]
    sha256 = "f1c800c39103762a896bf382ecee346392743ef9daffff0251639a86e3342fd7"
    url = "https://github.com/JuliaBinaryWrappers/obstack_jll.jl/releases/download/obstack-v1.2.3+0/obstack.v1.2.3.powerpc64le-linux-gnu.tar.gz"
[[obstack]]
arch = "x86_64"
git-tree-sha1 = "7db44c3fdbe64b614a402d91283edf42fceb3d3d"
libc = "glibc"
os = "linux"

    [[obstack.download]]
    sha256 = "eb2af9f6b553bbb68ad6b3a0316ebd65bdbb9aae4c7bd7b7052886418b3af826"
    url = "https://github.com/JuliaBinaryWrappers/obstack_jll.jl/releases/download/obstack-v1.2.3+0/obstack.v1.2.3.x86_64-linux-gnu.tar.gz"
[[obstack]]
arch = "x86_64"
git-tree-sha1 = "15d189ec056eb05b91511c2498f951552e0322ad"
libc = "musl"
os = "linux"

    [[obstack.download]]
    sha256 = "c4e5838a826fc95b36da62e39f1437b822a3e3bd8d0df66f4294f9e0964bd728"
    url = "https://github.com/JuliaBinaryWrappers/obstack_jll.jl/releases/download/obstack-v1.2.3+0/obstack.v1.2.3.x86_64-linux-musl.tar.gz"
